---
- name: Install packages on management servers
  hosts: management_servers
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Ensure VIM is at the latest version
      apt:
        name: vim
        state: latest
        update_cache: yes
